function [runs, summary] = runBenchmark(varargin)
%RUNBENCHMARK Run the repository's reproducible autonomous-driving benchmark.

root = fileparts(mfilename('fullpath'));
sampleRoot = fullfile(root, 'examples', 'autonomous-driving');
samples = struct( ...
    'Name', {'CARLA urban dusk', 'CARLA uneven illumination'}, ...
    'InputPath', { ...
        fullfile(sampleRoot, 'urban-dusk-input.jpg'), ...
        fullfile(sampleRoot, 'uneven-light-input.jpg')}, ...
    'ReferencePath', { ...
        '', ...
        fullfile(sampleRoot, 'uneven-light-reference.jpg')});

outputDirectory = fullfile(root, 'benchmark-results');
[runs, summary] = psoenhance.benchmark(samples, ...
    'OutputDirectory', outputDirectory, varargin{:});
end
