function statistics = precomputeStatistics(luminance, localWindowSize)
%PRECOMPUTESTATISTICS Compute image terms shared by every PSO candidate.

validateattributes(luminance, {'numeric'}, ...
    {'2d', 'nonempty', 'real', 'finite'}, mfilename, 'luminance');
validateattributes(localWindowSize, {'numeric'}, ...
    {'scalar', 'integer', 'odd', '>=', 3}, mfilename, 'localWindowSize');

window = true(localWindowSize);
kernel = ones(localWindowSize) ./ (localWindowSize * localWindowSize);
statistics = struct( ...
    'Image', luminance, ...
    'GlobalMean', mean(luminance(:)), ...
    'LocalMean', imfilter(luminance, kernel, 'symmetric', 'same'), ...
    'LocalStd', stdfilt(luminance, window), ...
    'WindowSize', localWindowSize);
end
