function generateReadmeAssets()
%GENERATEREADMEASSETS Reproduce README images and compact benchmark tables.

root = fileparts(fileparts(mfilename('fullpath')));
sampleRoot = fullfile(root, 'examples', 'autonomous-driving');
assetRoot = fullfile(root, 'docs', 'assets', 'autonomous-driving');
if ~exist(assetRoot, 'dir')
    mkdir(assetRoot);
end

samples = { ...
    'urban-dusk-input.jpg', ...
    'uneven-light-input.jpg'};
outputNames = { ...
    'urban-dusk-pso.jpg', ...
    'uneven-light-pso.jpg'};

for index = 1:numel(samples)
    inputImage = imread(fullfile(sampleRoot, samples{index}));
    enhanced = psoenhance.enhance(inputImage, ...
        'ObjectiveMode', 'pareto', ...
        'RandomSeed', 42, ...
        'SwarmSize', 18, ...
        'MaxIterations', 35, ...
        'OptimizationScale', 0.35);
    imwrite(enhanced, fullfile(assetRoot, outputNames{index}), ...
        'Quality', 92);
end

[~, summary] = runBenchmark( ...
    'Seeds', 1:5, ...
    'SwarmSize', 16, ...
    'MaxIterations', 30, ...
    'DisplayProgress', true);
writetable(summary, fullfile(root, 'benchmark-results', ...
    'benchmark-summary.csv'));
end
